apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  description: Everything related to artists.
  tags:
    - portal
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 1
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 2
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 3
      icon: dashboard
      type: admin-dashboard
spec:
  owner: team-a
  domain: artists
  type: service
