apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  description: Everything related to artists.
  tags:
    - portal
  links:
   
    - url: https://admin.example-org.com
      title: Admin Dashboard 1
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 2
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 3
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 4
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 5
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 6
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 7
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 8
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 9
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 10
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 11
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 12
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 13
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 14
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 15
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 16
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 17
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 18
      icon: dashboard
      type: admin-dashboard
spec:
  owner: team-a
  domain: artists
  type: service
