apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  description: |-
    Everything related to artists. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend lectus elit, et cursus libero varius non. Nulla pellentesque quis nisl ut cursus. Sed vitae nisi commodo, ornare eros vitae, imperdiet libero. Morbi ultrices dapibus posuere. Mauris pharetra consequat nisi, eu pulvinar lacus interdum vitae. Nulla venenatis, leo sit amet placerat vestibulum, justo tellus efficitur justo, at molestie ante lectus vehicula ligula. Curabitur vehicula viverra dapibus. Nam nec neque pharetra, fringilla nunc vel, maximus enim. Aliquam ullamcorper elementum libero sed dictum. Duis venenatis, odio maximus consectetur vulputate, risus tellus commodo dui, ut ornare orci nisl eget nunc. Cras semper ante faucibus lorem maximus, eget suscipit felis vestibulum. Suspendisse cursus ligula nec quam molestie, in fermentum ante cursus. Etiam bibendum dictum sapien, nec mollis metus dapibus id. Donec quis efficitur nulla.
    Sed molestie sem libero, quis cursus sem fringilla et. Pellentesque at nisl pharetra, fermentum ex in, tincidunt nisl. In ornare id nibh vitae dignissim. Nulla nec urna vel eros rutrum bibendum. Vestibulum dui nulla, mattis facilisis magna eu, maximus tempus nisi. Integer vulputate dui eu orci tempus, eu facilisis augue elementum. Quisque quis est bibendum, condimentum lacus in, lobortis ex. Ut mattis pellentesque ligula, at euismod mi finibus quis.
    Nulla nec viverra neque. Nam at dapibus lacus. Integer faucibus, mauris id hendrerit sagittis, odio purus condimentum eros, ac porta nisi diam et leo. Morbi efficitur, diam vel finibus venenatis, justo nulla mollis mauris, eu dictum tortor ex ac nisl. Pellentesque scelerisque viverra porttitor. Proin interdum aliquet diam vel aliquam. Cras sodales enim eget mollis elementum. Phasellus ultrices sagittis maximus. Nunc sodales lectus leo, sed semper magna porttitor placerat. Vestibulum tincidunt luctus molestie. Fusce vehicula, augue in cursus interdum, quam eros auctor ligula, a porttitor nunc ex a tortor. Ut pulvinar, orci nec suscipit rutrum, tellus dui posuere erat, ut tincidunt eros eros non leo.
    Nunc tristique nibh turpis, non maximus mi gravida euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce est felis, lacinia quis nunc eu, iaculis varius enim. In sit amet molestie odio, eu tempus arcu. Nullam consectetur purus ipsum, ac venenatis ante dignissim eget. Cras hendrerit mi ipsum, non aliquet velit iaculis vitae. Ut aliquet vehicula convallis. Quisque iaculis sem vel purus ultricies, et fringilla ex feugiat. Morbi lacus nisl, iaculis sed porttitor eget, eleifend nec ligula.
    Nam laoreet leo sit amet turpis mollis facilisis. Nullam euismod vestibulum porta. Sed ut congue tortor, non suscipit tellus. Nullam facilisis, odio in imperdiet convallis, nisi odio pulvinar odio, quis volutpat turpis nunc non leo. Integer eu augue non urna lacinia pharetra id nec nibh. Etiam eleifend mauris vel velit semper venenatis. Sed tincidunt eros lacus, a pulvinar dui volutpat ac. Vestibulum aliquam sed mi luctus pulvinar. Nullam est quam, ullamcorper vel tellus nec, ullamcorper aliquet tellus. Sed malesuada eros non erat placerat, quis bibendum magna laoreet. Maecenas luctus odio dolor, sit amet tempor erat scelerisque tempus. Morbi cursus, lorem at placerat rhoncus, ex erat maximus enim, in faucibus neque tortor sit amet neque.
  tags:
    - portal
  links:
   
    - url: https://admin.example-org.com
      title: Admin Dashboard 1
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 2
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 3
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 4
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 5
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 6
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 7
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 8
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 9
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 10
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 11
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 12
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 13
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 14
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 15
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 16
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 17
      icon: dashboard
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Admin Dashboard 18
      icon: dashboard
      type: admin-dashboard
spec:
  owner: team-a
  domain: artists
  type: service
